src/main/java/com/ubs/stores/ubs/StoresHasProductsController.java
package com.ubs.stores.ubs;

import com.ubs.stores.ubs.util.JsfUtil;
import com.ubs.stores.ubs.util.PaginationHelper;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("storesHasProductsController")
@SessionScoped
public class StoresHasProductsController implements Serializable {

    private StoresHasProducts current;
    private DataModel items = null;
    @EJB
    private com.ubs.stores.ubs.StoresHasProductsFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public StoresHasProductsController() {
    }

    public StoresHasProducts getSelected() {
        if (current == null) {
            current = new StoresHasProducts();
            current.setStoresHasProductsPK(new com.ubs.stores.ubs.StoresHasProductsPK());
            selectedItemIndex = -1;
        }
        return current;
    }

    private StoresHasProductsFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (StoresHasProducts) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new StoresHasProducts();
        current.setStoresHasProductsPK(new com.ubs.stores.ubs.StoresHasProductsPK());
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            current.getStoresHasProductsPK().setProduct(current.getProducts().getProductsPK().getProduct());
            current.getStoresHasProductsPK().setFileName(current.getProducts().getProductsPK().getFileName());
            current.getStoresHasProductsPK().setStoreName(current.getStores().getStoreName());
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("StoresHasProductsCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (StoresHasProducts) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            current.getStoresHasProductsPK().setProduct(current.getProducts().getProductsPK().getProduct());
            current.getStoresHasProductsPK().setFileName(current.getProducts().getProductsPK().getFileName());
            current.getStoresHasProductsPK().setStoreName(current.getStores().getStoreName());
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("StoresHasProductsUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (StoresHasProducts) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("StoresHasProductsDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public StoresHasProducts getStoresHasProducts(com.ubs.stores.ubs.StoresHasProductsPK id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = StoresHasProducts.class)
    public static class StoresHasProductsControllerConverter implements Converter {

        private static final String SEPARATOR = "#";
        private static final String SEPARATOR_ESCAPED = "\\#";

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            StoresHasProductsController controller = (StoresHasProductsController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "storesHasProductsController");
            return controller.getStoresHasProducts(getKey(value));
        }

        com.ubs.stores.ubs.StoresHasProductsPK getKey(String value) {
            com.ubs.stores.ubs.StoresHasProductsPK key;
            String values[] = value.split(SEPARATOR_ESCAPED);
            key = new com.ubs.stores.ubs.StoresHasProductsPK();
            key.setProduct(values[0]);
            key.setFileName(values[1]);
            key.setStoreName(values[2]);
            key.setSequence(Integer.parseInt(values[3]));
            return key;
        }

        String getStringKey(com.ubs.stores.ubs.StoresHasProductsPK value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value.getProduct());
            sb.append(SEPARATOR);
            sb.append(value.getFileName());
            sb.append(SEPARATOR);
            sb.append(value.getStoreName());
            sb.append(SEPARATOR);
            sb.append(value.getSequence());
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof StoresHasProducts) {
                StoresHasProducts o = (StoresHasProducts) object;
                return getStringKey(o.getStoresHasProductsPK());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + StoresHasProducts.class.getName());
            }
        }

    }

}

src/main/webapp/jsf/storesHasProducts/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateStoresHasProductsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateStoresHasProductsLabel_storesHasProductsPK_sequence}" for="storesHasProductsPK_sequence" />
                    <h:inputText id="storesHasProductsPK_sequence" value="#{storesHasProductsController.selected.storesHasProductsPK.sequence}" title="#{bundle.CreateStoresHasProductsTitle_storesHasProductsPK_sequence}" required="true" requiredMessage="#{bundle.CreateStoresHasProductsRequiredMessage_storesHasProductsPK_sequence}"/>
                    <h:outputLabel value="#{bundle.CreateStoresHasProductsLabel_acquiredPrice}" for="acquiredPrice" />
                    <h:inputText id="acquiredPrice" value="#{storesHasProductsController.selected.acquiredPrice}" title="#{bundle.CreateStoresHasProductsTitle_acquiredPrice}" required="true" requiredMessage="#{bundle.CreateStoresHasProductsRequiredMessage_acquiredPrice}"/>
                    <h:outputLabel value="#{bundle.CreateStoresHasProductsLabel_quantity}" for="quantity" />
                    <h:inputText id="quantity" value="#{storesHasProductsController.selected.quantity}" title="#{bundle.CreateStoresHasProductsTitle_quantity}" required="true" requiredMessage="#{bundle.CreateStoresHasProductsRequiredMessage_quantity}"/>
                    <h:outputLabel value="#{bundle.CreateStoresHasProductsLabel_products}" for="products" />
                    <h:selectOneMenu id="products" value="#{storesHasProductsController.selected.products}" title="#{bundle.CreateStoresHasProductsTitle_products}" required="true" requiredMessage="#{bundle.CreateStoresHasProductsRequiredMessage_products}">
                        <f:selectItems value="#{productsController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateStoresHasProductsLabel_stores}" for="stores" />
                    <h:selectOneMenu id="stores" value="#{storesHasProductsController.selected.stores}" title="#{bundle.CreateStoresHasProductsTitle_stores}" required="true" requiredMessage="#{bundle.CreateStoresHasProductsRequiredMessage_stores}">
                        <f:selectItems value="#{storesController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{storesHasProductsController.create}" value="#{bundle.CreateStoresHasProductsSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{storesHasProductsController.prepareList}" value="#{bundle.CreateStoresHasProductsShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateStoresHasProductsIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/jsf/storesHasProducts/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditStoresHasProductsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditStoresHasProductsLabel_storesHasProductsPK_sequence}" for="storesHasProductsPK_sequence" />
                    <h:inputText id="storesHasProductsPK_sequence" value="#{storesHasProductsController.selected.storesHasProductsPK.sequence}" title="#{bundle.EditStoresHasProductsTitle_storesHasProductsPK_sequence}" required="true" requiredMessage="#{bundle.EditStoresHasProductsRequiredMessage_storesHasProductsPK_sequence}"/>
                    <h:outputLabel value="#{bundle.EditStoresHasProductsLabel_acquiredPrice}" for="acquiredPrice" />
                    <h:inputText id="acquiredPrice" value="#{storesHasProductsController.selected.acquiredPrice}" title="#{bundle.EditStoresHasProductsTitle_acquiredPrice}" required="true" requiredMessage="#{bundle.EditStoresHasProductsRequiredMessage_acquiredPrice}"/>
                    <h:outputLabel value="#{bundle.EditStoresHasProductsLabel_quantity}" for="quantity" />
                    <h:inputText id="quantity" value="#{storesHasProductsController.selected.quantity}" title="#{bundle.EditStoresHasProductsTitle_quantity}" required="true" requiredMessage="#{bundle.EditStoresHasProductsRequiredMessage_quantity}"/>
                    <h:outputLabel value="#{bundle.EditStoresHasProductsLabel_products}" for="products" />
                    <h:selectOneMenu id="products" value="#{storesHasProductsController.selected.products}" title="#{bundle.EditStoresHasProductsTitle_products}" required="true" requiredMessage="#{bundle.EditStoresHasProductsRequiredMessage_products}">
                        <f:selectItems value="#{productsController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditStoresHasProductsLabel_stores}" for="stores" />
                    <h:selectOneMenu id="stores" value="#{storesHasProductsController.selected.stores}" title="#{bundle.EditStoresHasProductsTitle_stores}" required="true" requiredMessage="#{bundle.EditStoresHasProductsRequiredMessage_stores}">
                        <f:selectItems value="#{storesController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{storesHasProductsController.update}" value="#{bundle.EditStoresHasProductsSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditStoresHasProductsViewLink}"/>
                <br />
                <h:commandLink action="#{storesHasProductsController.prepareList}" value="#{bundle.EditStoresHasProductsShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditStoresHasProductsIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/jsf/storesHasProducts/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListStoresHasProductsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListStoresHasProductsEmpty}" rendered="#{storesHasProductsController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{storesHasProductsController.items.rowCount > 0}">
                    <h:outputText value="#{storesHasProductsController.pagination.pageFirstItem + 1}..#{storesHasProductsController.pagination.pageLastItem + 1}/#{storesHasProductsController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{storesHasProductsController.previous}" value="#{bundle.Previous} #{storesHasProductsController.pagination.pageSize}" rendered="#{storesHasProductsController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{storesHasProductsController.next}" value="#{bundle.Next} #{storesHasProductsController.pagination.pageSize}" rendered="#{storesHasProductsController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{storesHasProductsController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListStoresHasProductsTitle_storesHasProductsPK_sequence}"/>
                            </f:facet>
                            <h:outputText value="#{item.storesHasProductsPK.sequence}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListStoresHasProductsTitle_acquiredPrice}"/>
                            </f:facet>
                            <h:outputText value="#{item.acquiredPrice}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListStoresHasProductsTitle_quantity}"/>
                            </f:facet>
                            <h:outputText value="#{item.quantity}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListStoresHasProductsTitle_products}"/>
                            </f:facet>
                            <h:outputText value="#{item.products}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListStoresHasProductsTitle_stores}"/>
                            </f:facet>
                            <h:outputText value="#{item.stores}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{storesHasProductsController.prepareView}" value="#{bundle.ListStoresHasProductsViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{storesHasProductsController.prepareEdit}" value="#{bundle.ListStoresHasProductsEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{storesHasProductsController.destroy}" value="#{bundle.ListStoresHasProductsDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{storesHasProductsController.prepareCreate}" value="#{bundle.ListStoresHasProductsCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListStoresHasProductsIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/jsf/storesHasProducts/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewStoresHasProductsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewStoresHasProductsLabel_storesHasProductsPK_sequence}"/>
                    <h:outputText value="#{storesHasProductsController.selected.storesHasProductsPK.sequence}" title="#{bundle.ViewStoresHasProductsTitle_storesHasProductsPK_sequence}"/>
                    <h:outputText value="#{bundle.ViewStoresHasProductsLabel_acquiredPrice}"/>
                    <h:outputText value="#{storesHasProductsController.selected.acquiredPrice}" title="#{bundle.ViewStoresHasProductsTitle_acquiredPrice}"/>
                    <h:outputText value="#{bundle.ViewStoresHasProductsLabel_quantity}"/>
                    <h:outputText value="#{storesHasProductsController.selected.quantity}" title="#{bundle.ViewStoresHasProductsTitle_quantity}"/>
                    <h:outputText value="#{bundle.ViewStoresHasProductsLabel_products}"/>
                    <h:outputText value="#{storesHasProductsController.selected.products}" title="#{bundle.ViewStoresHasProductsTitle_products}"/>
                    <h:outputText value="#{bundle.ViewStoresHasProductsLabel_stores}"/>
                    <h:outputText value="#{storesHasProductsController.selected.stores}" title="#{bundle.ViewStoresHasProductsTitle_stores}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{storesHasProductsController.destroyAndView}" value="#{bundle.ViewStoresHasProductsDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewStoresHasProductsEditLink}"/>
                <br />
                <h:commandLink action="#{storesHasProductsController.prepareCreate}" value="#{bundle.ViewStoresHasProductsCreateLink}" />
                <br />
                <h:commandLink action="#{storesHasProductsController.prepareList}" value="#{bundle.ViewStoresHasProductsShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewStoresHasProductsIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>